# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.book import Book
from swagger_server import util


class GetBookByIdResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, status: str=None, message: str=None, book: Book=None):  # noqa: E501
        """GetBookByIdResponse - a model defined in Swagger

        :param status: The status of this GetBookByIdResponse.  # noqa: E501
        :type status: str
        :param message: The message of this GetBookByIdResponse.  # noqa: E501
        :type message: str
        :param book: The book of this GetBookByIdResponse.  # noqa: E501
        :type book: Book
        """
        self.swagger_types = {
            'status': str,
            'message': str,
            'book': Book
        }

        self.attribute_map = {
            'status': 'status',
            'message': 'message',
            'book': 'book'
        }

        self._status = status
        self._message = message
        self._book = book

    @classmethod
    def from_dict(cls, dikt) -> 'GetBookByIdResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetBookByIdResponse of this GetBookByIdResponse.  # noqa: E501
        :rtype: GetBookByIdResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this GetBookByIdResponse.


        :return: The status of this GetBookByIdResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this GetBookByIdResponse.


        :param status: The status of this GetBookByIdResponse.
        :type status: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def message(self) -> str:
        """Gets the message of this GetBookByIdResponse.


        :return: The message of this GetBookByIdResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this GetBookByIdResponse.


        :param message: The message of this GetBookByIdResponse.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def book(self) -> Book:
        """Gets the book of this GetBookByIdResponse.


        :return: The book of this GetBookByIdResponse.
        :rtype: Book
        """
        return self._book

    @book.setter
    def book(self, book: Book):
        """Sets the book of this GetBookByIdResponse.


        :param book: The book of this GetBookByIdResponse.
        :type book: Book
        """
        if book is None:
            raise ValueError("Invalid value for `book`, must not be `None`")  # noqa: E501

        self._book = book
